---
- hosts: all
  become: true

  tasks:
    - name: Install required system packages
      apt: 
        name: '{{ item }}' 
        state: latest 
        update_cache: yes
      loop: [ 'software-properties-common', 'wget', 'unzip' ]

    - name: Add nodejs source
      ansible.builtin.shell:
        cmd: curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -

    - name: Install nodejs
      apt:
        name: nodejs
        state: latest

    - name: Download pm2
      community.general.npm:
        name: pm2
        global: yes
        production: yes

- hosts: node
  become: true
  vars_files: vars/simvoni_vars.yml

  tasks:
    - name: Download and Unarchive Openethereum
      ansible.builtin.unarchive:
        src: "{{ openethereum_release }}"
        dest: /usr/local/bin
        remote_src: yes

    - name: Change file permission
      ansible.builtin.file:
        path: '/usr/local/bin/{{ item }}'
        state: file
        mode: '0755'
      loop: [ openethereum, openethereum-evm, ethkey, ethstore ]

    - name: Clone eth explorer
      ansible.builtin.git:
        repo: https://github.com/cekingx/explorer.git
        dest: '$HOME/eth-explorer'

# - hosts: webserver
#   become: true
#   vars_files: vars/simvoni_vars.yml

#   tasks:
#     - name: Add nodejs source
#       ansible.builtin.shell:
#         cmd: curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -

#     - name: Install nodejs
#       apt:
#         name: nodejs
#         state: latest

#     - name: Download pm2
#       community.general.npm:
#         name: pm2
#         global: yes
#         production: yes